name: testing
on:
  push:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Setup python
        uses: action/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Install requirements
        run: poetry install
      - name: pytest
        run: poetry run pytest -sv tests
